import * as FileSystem from "expo-file-system/legacy";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as XLSX from "xlsx";
import type { ReportFunctionMeta } from "../types/report";

function escapeHtml(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function functionMetaHtmlSection(meta: ReportFunctionMeta | null): string {
  if (!meta) return "";
  return `
  <div class="cover">
    <h1>Function details</h1>
    <table class="meta">
      <tr><th>Function Name</th><td>${escapeHtml(meta.functionName)}</td></tr>
      <tr><th>Date</th><td>${escapeHtml(meta.functionDate)}</td></tr>
      <tr><th>Mahal Name</th><td>${escapeHtml(meta.mahalName)}</td></tr>
      <tr><th>Function Hero/Heroine</th><td>${escapeHtml(meta.funPersionNames)}</td></tr>
    </table>
    ${
      meta.reportDate
        ? `<p class="sub">Report: ${escapeHtml(meta.reportDate)}${
            meta.generatedBy ? ` · ${escapeHtml(meta.generatedBy)}` : ""
          }</p>`
        : ""
    }
  </div>
  <hr class="sep"/>`;
}

function tableHtmlFromRows(rows: Record<string, unknown>[]): string {
  if (!rows.length) return "<p>No data</p>";
  const keys = Object.keys(rows[0]);
  const header = keys.map((k) => `<th>${escapeHtml(k)}</th>`).join("");
  const body = rows
    .map(
      (row) =>
        `<tr>${keys
          .map((k) => `<td>${escapeHtml(String(row[k] ?? ""))}</td>`)
          .join("")}</tr>`
    )
    .join("");
  return `<table><thead><tr>${header}</tr></thead><tbody>${body}</tbody></table>`;
}

const PDF_STYLES = `
  body{font-family:system-ui,sans-serif;font-size:11px;padding:12px;color:#222}
  .cover{border:2px solid #c2185b;border-radius:8px;padding:16px;margin-bottom:16px}
  .cover h1{color:#c2185b;font-size:18px;margin:0 0 12px}
  .meta{width:100%;border-collapse:collapse}
  .meta th,.meta td{border:1px solid #ccc;padding:8px;text-align:left}
  .meta th{width:35%;background:#fce4ec}
  .sub{color:#666;margin-top:8px}
  .sep{border:none;border-top:2px dashed #ccc;margin:20px 0}
  h2{font-size:16px;color:#c2185b;margin:16px 0 8px}
  table.data{border-collapse:collapse;width:100%}
  table.data th,table.data td{border:1px solid #ccc;padding:6px;text-align:left}
  table.data th{background:#f5eef1}
`;

export function buildReportPdfHtml(
  sections: { title: string; rows: Record<string, unknown>[] }[],
  meta: ReportFunctionMeta | null
): string {
  const cover = functionMetaHtmlSection(meta);
  const bodies = sections
    .map(
      (s) =>
        `<h2>${escapeHtml(s.title)}</h2><div class="data">${tableHtmlFromRows(s.rows)}</div>`
    )
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>${PDF_STYLES}</style></head><body>${cover}${bodies}</body></html>`;
}

export function rowsToHtmlTable(
  rows: Record<string, unknown>[],
  title: string,
  meta?: ReportFunctionMeta | null
): string {
  return buildReportPdfHtml([{ title, rows }], meta ?? null);
}

function metaSheetRows(meta: ReportFunctionMeta): Record<string, string>[] {
  return [
    { Field: "Function Name", Value: meta.functionName },
    { Field: "Date", Value: meta.functionDate },
    { Field: "Mahal Name", Value: meta.mahalName },
    { Field: "Function Hero/Heroine", Value: meta.funPersionNames },
    ...(meta.reportDate
      ? [{ Field: "Report Date", Value: meta.reportDate }]
      : []),
    ...(meta.generatedBy
      ? [{ Field: "Generated By", Value: meta.generatedBy }]
      : []),
  ];
}

export async function shareExcel(
  rows: Record<string, unknown>[],
  fileName: string,
  sheetName: string,
  meta?: ReportFunctionMeta | null
) {
  const wb = XLSX.utils.book_new();
  if (meta) {
    const metaWs = XLSX.utils.json_to_sheet(metaSheetRows(meta));
    XLSX.utils.book_append_sheet(wb, metaWs, "Function");
  }
  const ws = XLSX.utils.json_to_sheet(rows.length ? rows : [{ note: "No data" }]);
  const safeSheet = sheetName.replace(/[[\]:*?/\\]/g, "_").slice(0, 31) || "Sheet1";
  XLSX.utils.book_append_sheet(wb, ws, safeSheet);
  const base64 = XLSX.write(wb, { type: "base64", bookType: "xlsx" });
  const path = `${FileSystem.cacheDirectory ?? ""}${fileName}`;
  await FileSystem.writeAsStringAsync(path, base64, {
    encoding: FileSystem.EncodingType.Base64,
  });
  await Sharing.shareAsync(path, {
    mimeType:
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    dialogTitle: fileName,
  });
}

export async function sharePdfFromHtml(html: string, dialogTitle: string) {
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, {
    mimeType: "application/pdf",
    dialogTitle,
    UTI: "com.adobe.pdf",
  });
}

export async function sharePdfReport(
  sections: { title: string; rows: Record<string, unknown>[] }[],
  dialogTitle: string,
  meta?: ReportFunctionMeta | null
) {
  const html = buildReportPdfHtml(sections, meta ?? null);
  await sharePdfFromHtml(html, dialogTitle);
}
